./build/MainRayTracing 9spheres
./build/MainRayTracing ballOnFloorScene
./build/MainRayTracing emptyScene
./build/MainRayTracing glassStrawScene
./build/MainRayTracing GoTScene
./build/MainRayTracing meshMonkey
./build/MainRayTracing meshScene
./build/MainRayTracing phongReflexionScene
./build/MainRayTracing polygonScene
./build/MainRayTracing refractionCylinderScene
./build/MainRayTracing refractionScene
./build/MainRayTracing singleWallScene
./build/MainRayTracing tableScene
./build/MainRayTracing testScene
./build/MainRayTracing transparentShadow
./build/MainRayTracing atalanteStl
./build/MainRayTracing atalanteStlDisco
./build/MainRayTracing atalanteObj
